package psychlua;

#if FEATURE_PSYCH_LUA
import funkin.util.Constants;

class LuaApiPrelude
{
  public static function source():String
  {
    final luaSliceVersion:String = Constants.LUASLICE_VERSION.charAt(0) == 'v' ? Constants.LUASLICE_VERSION.substr(1) : Constants.LUASLICE_VERSION;

    return [
      "LuaSlice = LuaSlice or {}",
      'LuaSlice.version = \'${luaSliceVersion}\'',
      "luaslice = LuaSlice",
      "function LuaSlice.versionAtLeast(version) local function parts(v) local a,b,c = tostring(v):match('(%d+)%.(%d+)%.(%d+)'); return tonumber(a) or 0, tonumber(b) or 0, tonumber(c) or 0 end; local a,b,c = parts(LuaSlice.version); local x,y,z = parts(version); if a ~= x then return a > x end; if b ~= y then return b > y end; return c >= z end",
      "function requiresLuaSlice(version) if not LuaSlice.versionAtLeast(version) then debugPrint('This script needs LuaSlice ' .. tostring(version) .. '+') return false end return true end",
      "local function v(value, fallback) if value == nil then return fallback end return value end",
      "local function tbl(value) return type(value) == 'table' end",
      "local __luaDeprecationWarned = {}",
      "local function __deprecated(oldName, newName) local key = tostring(oldName); if __luaDeprecationWarned[key] then return end; __luaDeprecationWarned[key] = true; if debugWarn ~= nil then debugWarn(key .. ' is old; use ' .. tostring(newName) .. ' instead.') elseif debugPrint ~= nil then debugPrint(key .. ' is old; use ' .. tostring(newName) .. ' instead.') end end",
      "LuaSlice.api = LuaSlice.api or { entries = {} }",
      "LuaSlice.api.entries = {}",
      "local function __api(name, category, description, args, example, deprecated, replacement) LuaSlice.api.entries[#LuaSlice.api.entries + 1] = { name = name, category = category, description = description, args = args or {}, example = example or '', deprecated = deprecated == true, replacement = replacement or '' } end",
      "function LuaSlice.api.list(category) local out = {}; for _, e in ipairs(LuaSlice.api.entries) do if category == nil or e.category == category then out[#out + 1] = e end end; return out end",
      "function LuaSlice.api.find(name) for _, e in ipairs(LuaSlice.api.entries) do if e.name == name then return e end end return nil end",
      "function LuaSlice.api.docs() local lines = {'# LuaSlice Lua API', ''}; for _, e in ipairs(LuaSlice.api.entries) do lines[#lines + 1] = '## ' .. e.name; lines[#lines + 1] = e.description or ''; if e.replacement ~= '' then lines[#lines + 1] = 'Use: ' .. e.replacement end; if e.example ~= '' then lines[#lines + 1] = 'Example: ' .. e.example end; lines[#lines + 1] = '' end; return table.concat(lines, '\\n') end",
      "function LuaSlice.api.writeDocs(path) return writeTextFile(path or 'LuaSlice Lua API.md', LuaSlice.api.docs()) end",
      "LuaSlice.layers = LuaSlice.layers or { background = -1000, stage = 0, characters = 300, foreground = 700, hud = 900, top = 1000 }",
      "local function __layerZ(layer) if type(layer) == 'number' then return layer end; return LuaSlice.layers[tostring(layer or '')] or 0 end",
      "local __luaTweenFunction = tween",
      "function addLuaMainMenu(id, position, target, assetPath, animName) return addLuaMainMenuItem(id, assetPath or 'images:mainmenu/storymode', v(position, 999), animName or 'storymode', target or '') end",
      "function makeLuaMenuSimple(id, items, x, y, spacing) local sp = v(spacing, 34); local ok = createLuaMenu(id, items or {}, v(x, 80), v(y, 120), 600, 'hud', 'white', 'yellow'); setLuaMenuPosition(id, v(x, 80), v(y, 120), sp); return ok end",
      "function makeLuaImageMenuSimple(id, items, x, y, spacing) return createLuaImageMenu(id, items or {}, v(x, 80), v(y, 120), v(spacing, 95), 'hud', {}) end",
      "function initLuaShader(name, tag) return initLuaShaderRaw(name, tag) end",
      "function makeLuaShader(tag, pathOrSource, vertexPathOrSource) if pathOrSource == nil then return initLuaShader(tag) end return createShader(tag, pathOrSource, vertexPathOrSource) end",
      "function setLuaShader(tag, target) return applyShader(tag, target) end",
      "function setShaderOnSprite(sprite, tag) return applyShader(tag, sprite) end",
      "function removeLuaShader(target) return clearShader(target) end",
      "function setLuaCameraShader(tag, camera) return applyCameraShader(tag, camera or 'game') end",
      "function removeLuaCameraShader(camera) return clearCameraShader(camera or 'game') end",
      "function setLuaShaderFloatSimple(tag, name, value) return setShaderFloat(tag, name, value) end",
      "debug = debug or {}",
      "debug.print = function(message) return debugPrint(message) end",
      "debug.info = function(message) return debugInfo(message) end",
      "debug.warn = function(message) return debugWarn(message) end",
      "debug.error = function(message) return debugError(message) end",
      "property = property or {}",
      "property.get = function(path) return getProperty(path) end",
      "property.set = function(path, value) return setProperty(path, value) end",
      "property.setMany = function(target, values) return setProperties(target, values or {}) end",
      "property.ref = function(path) return { get = function() return getPropertyRef(path) end, set = function(value) return setPropertyRef(path, value) end, path = path } end",
      "window = window or {}",
      "window.setTitle = function(title) return setLuaWindowTitle(tostring(title or 'LuaSlice')) end",
      "sprite = sprite or {}",
      "sprite.create = function(tag, data, x, y) if tbl(data) then local ok = data.animated and loadSparrow(tag, data.image or data.asset or '', v(data.x, 0), v(data.y, 0)) or loadGraphic(tag, data.image or data.asset or '', v(data.x, 0), v(data.y, 0)); if data.alpha ~= nil then setObjectAlpha(tag, data.alpha) end; if data.scale ~= nil then setObjectScale(tag, data.scale, data.scale) end; if data.camera ~= nil then setObjectCamera(tag, data.camera) end; if data.layer ~= nil then setObjectZIndex(tag, __layerZ(data.layer)) elseif data.front ~= nil then setObjectZIndex(tag, data.front and LuaSlice.layers.top or LuaSlice.layers.stage) end; return ok end; return loadGraphic(tag, data or '', v(x, 0), v(y, 0)) end",
      "sprite.add = function(tag, options) if tbl(options) and options.layer ~= nil then setObjectZIndex(tag, __layerZ(options.layer)) end; return objectExists(tag) end",
      "sprite.remove = function(tag) return removeSprite(tag) end",
      "sprite.exists = function(tag) return objectExists(tag) end",
      "sprite.set = function(tag, values) return setProperties(tag, values or {}) end",
      "sprite.setAlpha = function(tag, value) if type(value) ~= 'number' then debug.warn('sprite.setAlpha expected a number for alpha.') return false end return setObjectAlpha(tag, value) end",
      "sprite.setCamera = function(tag, camera) return setObjectCamera(tag, camera) end",
      "sprite.setLayer = function(tag, layer) return setObjectZIndex(tag, __layerZ(layer)) end",
      "group = group or {}",
      "LuaSlice.groups = LuaSlice.groups or {}",
      "group.create = function(name) LuaSlice.groups[tostring(name)] = LuaSlice.groups[tostring(name)] or {}; return true end",
      "group.add = function(name, tag) group.create(name); if objectExists(tag) then local g = LuaSlice.groups[tostring(name)]; g[#g + 1] = tag; return true end return false end",
      "group.each = function(name, callback) local g = LuaSlice.groups[tostring(name)] or {}; for _, tag in ipairs(g) do if objectExists(tag) then callback(tag) end end end",
      "group.set = function(name, values) group.each(name, function(tag) setProperties(tag, values or {}) end); return true end",
      "group.setAlpha = function(name, alpha) group.each(name, function(tag) setObjectAlpha(tag, alpha) end); return true end",
      "group.setLayer = function(name, layer) group.each(name, function(tag) setObjectZIndex(tag, __layerZ(layer)) end); return true end",
      "group.tween = function(name, values, duration, options) options = options or {}; local i = 0; group.each(name, function(tag) i = i + 1; tween.to(tag, values or {}, duration or 1, { ease = options.ease or 'linear', tag = (options.tag or tostring(name)) .. '_' .. tostring(i) }) end); return true end",
      "group.remove = function(name, tag) local g = LuaSlice.groups[tostring(name)]; if not g then return false end; if tag == nil then for _, t in ipairs(g) do if objectExists(t) then removeSprite(t) end end; LuaSlice.groups[tostring(name)] = {}; return true end; for i, t in ipairs(g) do if t == tag then table.remove(g, i); return true end end return false end",
      "camera = camera or {}",
      "camera.setZoom = function(cameraName, zoom) if zoom == nil then return setCamZoom(cameraName, 'game') end return setCameraZoom(cameraName or 'game', zoom) end",
      "camera.flash = function(cameraName, color, duration) return cameraFlash(cameraName or 'game', color or 'FFFFFF', v(duration, 1)) end",
      "camera.shake = function(cameraName, intensity, duration) return cameraShake(cameraName or 'game', v(intensity, 0.01), v(duration, 0.5)) end",
      "camera.tween = function(cameraName, values, duration, ease) local targets = { game = 'camGame', hud = 'camHUD', other = 'camOther' }; local target = targets[cameraName] or cameraName or 'camGame'; return __luaTweenFunction('__camera_' .. tostring(cameraName or 'game'), target, values or {}, v(duration, 1), ease or 'linear') end",
      "shader = shader or {}",
      "shader.init = function(name, tag) return initLuaShader(name, tag) end",
      "shader.make = function(tag, path, vertex) return makeLuaShader(tag, path, vertex) end",
      "shader.apply = function(target, tag) return setShaderOnSprite(target, tag) end",
      "shader.remove = function(target) return removeLuaShader(target) end",
      "shader.exists = function(tag) return luaShaderExists(tag) end",
      "shader.setColor = function(tag, property, color) return setShaderColor(tag, property or 'color', color or '#FFFFFF') end",
      "shader.tween = function(tag, property, from, to, duration, ease, tweenTag) return tweenShaderFloat(tag, property or 'amount', v(from, 0), v(to, 1), v(duration, 1), ease or 'linear', tweenTag) end",
      "character = character or {}",
      "character.exists = function(target) return objectExists(target) end",
      "character.playAnim = function(target, animation, force, reversed, frame) if not objectExists(target) then return false end return playAnim(target, animation, force == true, reversed == true, v(frame, 0)) end",
      "stage = stage or {}",
      "stage.exists = function(id) return luaStageExists(id) end",
      "stage.change = function(id) return changeStage(id) end",
      "option = option or {}",
      "option.exists = function(key) return hasLuaOption(key) end",
      "save = save or {}",
      "save.get = function(key, fallback) return getLuaSave(key, fallback) end",
      "save.set = function(key, value) return setLuaSave(key, value) end",
      "save.flush = function() return flushSave() end",
      "sound = sound or {}",
      "sound.play = function(tag, key, volume, looped) return playSound(tag, key, v(volume, 1), looped == true) end",
      "sound.stop = function(tag) return stopSound(tag) end",
      "sound.exists = function(tag) return soundExists(tag) end",
      "script = script or {}",
      "script.disableHook = function(name) return disableLuaHook(name) end",
      "script.enableHook = function(name) return enableLuaHook(name) end",
      "script.getPath = function() return getCurrentLuaScriptPath() end",
      "script.getName = function() local path = script.getPath(); return path:match('([^/]+)$') or path end",
      "script.reload = function() return reloadLuaScripts() end",
      "script.stop = function() return stopCurrentLuaScript() end",
      "script.setPriority = function(priority) return setCurrentLuaScriptPriority(priority) end",
      "tween = {}",
      "local function __ensureTweenHook() if _G.__luaTweenHookReady then return end; _G.__luaTweenHookReady = true; local old = onTweenCompleted; _G.onTweenCompleted = function(tag) if old then old(tag) end; local cb = _G.__luaTweenCallbacks and _G.__luaTweenCallbacks[tag]; if cb then _G.__luaTweenCallbacks[tag] = nil; cb(tag) end end end",
      "tween.to = function(target, values, duration, options) options = options or {}; local tag = options.tag or target; if options.onComplete then __ensureTweenHook(); _G.__luaTweenCallbacks = _G.__luaTweenCallbacks or {}; _G.__luaTweenCallbacks[tag] = options.onComplete end; return __luaTweenFunction(tag, target, values or {}, v(duration, 1), options.ease or 'linear') end",
      "tween.cancel = function(tag) return cancelTween(tag) end",
      "tween.pause = function(tag) return pauseTween(tag) end",
      "tween.resume = function(tag) return resumeTween(tag) end",
      "timer = timer or {}",
      "local function __ensureTimerHook() if _G.__luaTimerHookReady then return end; _G.__luaTimerHookReady = true; local old = onTimerCompleted; _G.onTimerCompleted = function(tag, loopsLeft) if old then old(tag, loopsLeft) end; if _G.__luaTimerCallbacks and _G.__luaTimerCallbacks[tag] then _G.__luaTimerCallbacks[tag](loopsLeft); if loopsLeft <= 0 then _G.__luaTimerCallbacks[tag] = nil end end end end",
      "timer.after = function(delay, callback) __ensureTimerHook(); local tag = '__after_' .. tostring(callback); _G.__luaTimerCallbacks = _G.__luaTimerCallbacks or {}; _G.__luaTimerCallbacks[tag] = callback; runTimer(tag, delay, 1); return tag end",
      "timer.every = function(delay, callback) __ensureTimerHook(); local tag = '__every_' .. tostring(callback); _G.__luaTimerCallbacks = _G.__luaTimerCallbacks or {}; _G.__luaTimerCallbacks[tag] = callback; runTimer(tag, delay, 0); return tag end",
      "song = song or {}",
      "song.getPosition = function() return getSongPosition() end",
      "local function __ensureBeatHook() if _G.__luaBeatHookReady then return end; _G.__luaBeatHookReady = true; local old = onBeatHit; _G.onBeatHit = function(beat) if old then old(beat) end; local b = beat or curBeat; if _G.__luaBeatCallbacks and _G.__luaBeatCallbacks[b] then _G.__luaBeatCallbacks[b](b) end end end",
      "local function __ensureStepHook() if _G.__luaStepHookReady then return end; _G.__luaStepHookReady = true; local old = onStepHit; _G.onStepHit = function(step) if old then old(step) end; local s = step or curStep; if _G.__luaStepCallbacks and _G.__luaStepCallbacks[s] then _G.__luaStepCallbacks[s](s) end end end",
      "song.atBeat = function(beat, callback) __ensureBeatHook(); _G.__luaBeatCallbacks = _G.__luaBeatCallbacks or {}; _G.__luaBeatCallbacks[beat] = callback end",
      "song.atStep = function(step, callback) __ensureStepHook(); _G.__luaStepCallbacks = _G.__luaStepCallbacks or {}; _G.__luaStepCallbacks[step] = callback end",
      "song.betweenBeats = function(firstBeat, lastBeat, callback) return event.on('beat', function(beat) if beat >= firstBeat and beat <= lastBeat then callback(beat) end end) end",
      "event = event or {}",
      "local function __eventList(name) _G.__luaEventCallbacks = _G.__luaEventCallbacks or {}; _G.__luaEventCallbacks[name] = _G.__luaEventCallbacks[name] or {}; return _G.__luaEventCallbacks[name] end",
      "local function __runEventList(name, ...) if not _G.__luaEventCallbacks or not _G.__luaEventCallbacks[name] then return end; for i, cb in ipairs(_G.__luaEventCallbacks[name]) do cb(...) end end",
      "local function __ensureNamedEventHook(name) if name == 'beat' and not _G.__luaNamedBeatHookReady then _G.__luaNamedBeatHookReady = true; __ensureBeatHook(); local old = onBeatHit; _G.onBeatHit = function(beat) if old then old(beat) end; __runEventList('beat', beat or curBeat) end elseif name == 'step' and not _G.__luaNamedStepHookReady then _G.__luaNamedStepHookReady = true; __ensureStepHook(); local old = onStepHit; _G.onStepHit = function(step) if old then old(step) end; __runEventList('step', step or curStep) end elseif name == 'songStart' and not _G.__luaSongStartHookReady then _G.__luaSongStartHookReady = true; local old = onSongStart; _G.onSongStart = function() if old then old() end; __runEventList('songStart') end elseif name == 'update' and not _G.__luaUpdateHookReady then _G.__luaUpdateHookReady = true; local old = onUpdate; _G.onUpdate = function(elapsed) if old then old(elapsed) end; __runEventList('update', elapsed) end end end",
      "event.on = function(name, callback) __ensureNamedEventHook(name); table.insert(__eventList(name), callback); return callback end",
      "event.once = function(name, valueOrCallback, callback) local wanted = callback and valueOrCallback or nil; local cb = callback or valueOrCallback; local wrapper; wrapper = function(...) local first = select(1, ...); if wanted ~= nil and first ~= wanted then return end; cb(...); if _G.__luaEventCallbacks and _G.__luaEventCallbacks[name] then for i, item in ipairs(_G.__luaEventCallbacks[name]) do if item == wrapper then table.remove(_G.__luaEventCallbacks[name], i); break end end end end; return event.on(name, wrapper) end",
      "options = options or {}",
      "options.page = function(id, config) config = config or {}; createLuaOptionPage(id, config.name or config.title or id, v(config.position, -1)); for _, item in ipairs(config.items or {}) do local kind = item.type or 'checkbox'; if kind == 'checkbox' then addLuaCheckbox(id, item.key, item.name or item.label or item.key, item.description or '', item.default == true) elseif kind == 'number' then addLuaNumber(id, item.key, item.name or item.label or item.key, item.description or '', v(item.default, 0), v(item.min, 0), v(item.max, 100), v(item.step, 1), v(item.precision, 0)) elseif kind == 'enum' then addLuaEnum(id, item.key, item.name or item.label or item.key, item.description or '', item.values or {}, tostring(item.default or '')) end end return true end",
      "__api('LuaSlice.api.list', 'docs', 'Returns registered LuaSlice helper entries.', {'category?'}, 'for _, api in ipairs(LuaSlice.api.list()) do debug.info(api.name) end')",
      "__api('LuaSlice.api.writeDocs', 'docs', 'Writes a markdown API reference from the live registry.', {'path?'}, \"LuaSlice.api.writeDocs('LuaSlice Lua API.md')\")",
      "__api('sprite.create', 'sprite', 'Creates a Lua sprite from a table or image path.', {'tag','data'}, \"sprite.create('box', { image = 'menuDesat', x = 20, y = 20, layer = 'hud' })\")",
      "__api('sprite.setLayer', 'sprite', 'Moves a sprite to a named or numeric z layer.', {'tag','layer'}, \"sprite.setLayer('box', 'top')\")",
      "__api('group.create', 'group', 'Creates a simple Lua tag group.', {'name'}, \"group.create('hudStuff')\")",
      "__api('group.add', 'group', 'Adds an existing Lua object tag to a group.', {'name','tag'}, \"group.add('hudStuff', 'box')\")",
      "__api('group.set', 'group', 'Sets multiple properties on every valid object in a group.', {'name','values'}, \"group.set('hudStuff', { alpha = 0.5 })\")",
      "__api('group.tween', 'group', 'Tweens every valid object in a group.', {'name','values','duration','options?'}, \"group.tween('hudStuff', { alpha = 0 }, 0.5)\")",
      "__api('shader.init', 'shader', 'Loads a shader by name or tag.', {'name','tag?'}, \"shader.init('glitchShader')\")",
      "__api('shader.apply', 'shader', 'Applies a shader to a Lua sprite, character, or named stage object.', {'target','tag'}, \"shader.apply('object:streetLamp', 'glitchShader')\")",
      "__api('shader.exists', 'shader', 'Checks whether a shader tag is loaded.', {'tag'}, \"shader.exists('glitchShader')\")",
      "__api('shader.setColor', 'shader', 'Sets a color property on a supported shader.', {'tag','property','color'}, \"shader.setColor('rim', 'color', '#52351D')\")",
      "__api('window.setTitle', 'window', 'Changes the game window title.', {'title'}, \"window.setTitle('LuaSlice Test')\")",
      "__api('character.playAnim', 'character', 'Safely plays a character animation.', {'target','animation','force?'}, \"character.playAnim('dad', 'singLEFT')\")",
      "__api('stage.exists', 'stage', 'Checks whether a stage is registered.', {'id'}, \"stage.exists('mainStage')\")",
      "__api('tween.pause', 'tween', 'Pauses a tagged tween.', {'tag'}, \"tween.pause('boyfriend')\")",
      "__api('song.betweenBeats', 'song', 'Runs a callback for beats in an inclusive range.', {'firstBeat','lastBeat','callback'}, \"song.betweenBeats(64, 96, function(beat) end)\")",
      "__api('options.page', 'options', 'Creates a table-configured options page.', {'id','config'}, \"options.page('example', { name = 'Example', items = {} })\")",
      "__api('script.setPriority', 'script', 'Sets this script order for later hooks. Higher values run first.', {'priority'}, \"script.setPriority(10)\")",
      "__api('save.get', 'save', 'Reads a persistent Lua save value.', {'key','fallback?'}, \"save.get('coins', 0)\")",
      "__api('save.set', 'save', 'Writes a persistent Lua save value.', {'key','value'}, \"save.set('coins', 10)\")",
      "__api('debug.warn', 'debug', 'Logs a warning through LuaSlice.', {'message'}, \"debug.warn('careful')\")",
      "if makeLuaSprite ~= nil then local __old_makeLuaSprite = makeLuaSprite; function makeLuaSprite(...) __deprecated('makeLuaSprite', 'sprite.create'); return __old_makeLuaSprite(...) end end",
      "if addLuaSprite ~= nil then local __old_addLuaSprite = addLuaSprite; function addLuaSprite(...) __deprecated('addLuaSprite', 'sprite.add'); return __old_addLuaSprite(...) end end",
      "return true"
    ].join("\n");
  }
}
#end
